baseURL = 'https://orca.pdx.edu/'
languageCode = 'en-us'
title = 'Orca Accelerator'
theme = ['hugo-book', 'hugo-notice', 'hugo-admonitions']
enableGitInfo = true

[params]

BookTheme = 'auto'
BookRepo = 'https://github.com/orca-accelerator/orca-website'
BookCommitPath = 'commit'
BookSection = '*'
BookLogo = 'logo.png'
BookFavicon = 'favicon.png'

[markup]
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    style = 'bw'
